apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  username: bWF4
  password: MTIzNA==

---

apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  namespace: stark-cluster
  labels:
    service: jenkins-srv
spec:
  containers:
  - name: jenkins-demo
    image: ghostgoose33/get-python:v1
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: test-secret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: test-secret
          key: password


---
kind: Service
apiVersion: v1
metadata:
  name: ssh
  namespace: jenkins-srv
spec:
  selector:
    service: jenkins-srvs
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22  
  type: LoadBalancer

---
kind: Service
apiVersion: v1
metadata:
  name: registry
  namespace: jenkins-srv
spec:
  selector:
    service: jenkins-srvs
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
