kind: Service
apiVersion: v1
metadata:
  name: registry
  namespace: stark-cluster
spec:
  selector:
    service: jenkins-srvs
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer

---

apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  namespace: stark-cluster
  labels:
    service: jenkins-srvs
spec:
  containers:
  - name: jenkins-demo
    image: 100.71.71.71/get-python:3rt3y3h

