---
kind: Service
apiVersion: v1
metadata:
  namespace: production
  name: get-service-{{ .Values.deploy.version }}
  labels:
    app: get
spec:
  selector:
    app: get
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: get-deployment-{{ .Values.deploy.version }}
spec:
  selector:
    matchLabels:
      app: get
  replicas: 1
  template:
    metadata:
      labels:
        app: get
        version: {{ .Values.deploy.version }}

    spec:
      containers:
      - name: get
        image: "{{ .Values.image.repository }}/get-service:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5003
        env:
        - name: URL_DB
          valueFrom:
            configMapKeyRef:
              name: services-address
              key: URL_DB
