---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.app.name }}
spec:
  host: {{ .Values.app.name }}
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app.name }}
spec:
  hosts:
  - "*"
  gateways:
  - app-gateway
  http:
    - route:
      - destination:
          host: {{ .Values.app.name }}
          subset: v1
        weight: {{ .Values.weight.v1 }}
      - destination:
          host: {{ .Values.app.name }}
          subset: v2
        weight: {{ .Values.weight.v2 }}
---
