---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Values.app.name }}-{{ .Values.deploy.version }}"
  labels:
    app: "{{ .Values.app.name }}-{{ .Values.deploy.version }}"
    version: {{ .Values.deploy.version }}
spec:
  selector:
    app: "{{ .Values.app.name }}-{{ .Values.deploy.version }}"
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: ui-deployment-{{ .Values.deploy.version }}

spec:
  selector:
    matchLabels:
      app: "{{ .Values.app.name }}-{{ .Values.deploy.version }}"
      version: {{ .Values.deploy.version }}
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Values.app.name }}-{{ .Values.deploy.version }}"
        version: {{ .Values.deploy.version }}
    spec:
      containers:
      - name: "{{ .Values.app.name }}-{{ .Values.deploy.version }}"
        image: "{{ .Values.image.repository }}/ui-service:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        env:
        - name: POST_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: services-address-{{ .Values.conf.ver }}
              key: POST_SERVICE_URL
        - name: VIEW_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: services-address-{{ .Values.conf.ver }}
              key: VIEW_SERVICE_URL
